INSERT INTO ACCOUNTS (PERSONA, SALDO) VALUES ('Isaias', 1000);
INSERT INTO ACCOUNTS (PERSONA, SALDO) VALUES ('Jhon', 2000);

INSERT INTO BANKS (NAME, FULL_TRANSFER) VALUES ("El banco financiero", 0);
